### ISSUE TITLE
Issues Extracting USB

### ISSUE THREAD

**Issue by the16bitgamer** [koolkdev/wfs-tools#4]
Wii U is running 5.5.5 U and I am running Tiramisu. I keep getting the Error: Unexpected WFS version (bad key?) every time I've tried to extract my Wii U formatted USB. I've used the included NAND backup utility which comes with Tiramisu, and created multiple backups of the opt.bin, however I've had no luck.

Running the Win version in Windows 10, tried to run it with both the USB and a img of the USB made with Win32DiskImager

**Comment by koolkdev** [comment]
Can you post the command line that you are using?

**Comment by the16bitgamer** [comment]
Sure thing wfs-extract --input \\.\PhysicalDrive4 --output dump_dir --otp otp.bin --seeprom seeprom.bin
I've also attached an image to show the command line, power shell, and the directory I was using in the same window. Please let me know what I am doing wrong.
![image](https://user-images.githubusercontent.com/32138883/155387051-bbb6836b-026e-4722-b593-83c83eec3051.png)

**Comment by Sevenanths** [comment]
A long time ago, my Wii U decided to bork my USB drive. It was no longer recognised by the system, and gone were my saves. I have always kept onto the flash drive, because I hoped one day I would be able to read its contents. I am glad this program exists, but I too get this error:

![image](https://user-images.githubusercontent.com/6349952/170878113-48108887-abda-4cbb-8881-99cae8dc28ec.png)

Is there a way I would be able to get more information on what goes wrong etc? This way I could try and troubleshoot the issue myself. Thanks!

**Comment by godreborn** [comment]
I think I know the answer to your issue.  you haven't specified "type" if it's mlc or usb.  I was getting the same error with the injector.

**Comment by koolkdev** [comment]
Yes that is the issue with the provided command, without the type parameter it defaults to usb. (Sorry for the delayed response)
